import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useQuery } from 'react-query';
import styles from '../styles/Home.module.scss';
import { IPlayer } from './team/[id]';

const apiKey = process.env.NEXT_PUBLIC_API_KEY;

export interface ITeam {
    id: number;
    crestUrl: string;
    shortName: string;
    founded: string;
    venue: string;
    squad: IPlayer[];
}

const fetchPrem = async () => {
    const res = await fetch('https://api.football-data.org/v2/competitions/PL/teams', {
        headers: {
            'X-Auth-Token': `${apiKey}`,
        },
    });
    return res.json();
};

export default function Home(): JSX.Element {
    const { data, status } = useQuery('prem', fetchPrem, { staleTime: Infinity });

    const teams: ITeam[] = data?.teams;

    console.log(data, status);
    return (
        <div>
            <Head>
                <title>Football API</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Football API</h1>
                <div className={styles.teams}>
                    {teams?.map((team) => (
                        <div className={styles.team} key={team.id}>
                            <div>
                                <Link href={`team/${team.id}`}>
                                    <a>
                                        <Image
                                            width={80}
                                            height={`auto`}
                                            className={styles.crest}
                                            src={team.crestUrl}
                                            alt={team.shortName}
                                        />
                                    </a>
                                </Link>
                            </div>
                            <p>{team.shortName}</p>
                            <p>{`Founded ${team.founded}`}</p>
                            <p>{`Plays at ${team.venue}`}</p>
                        </div>
                    ))}
                </div>
            </main>
        </div>
    );
}
